[project]
name = "marimo-notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.0.0",
    "duckdb>=1.4.3",
    "google-genai>=1.56.0",
    "kubernetes>=34.1.0",
    "marimo[sql]>=0.18.4",
    "numpy>=2.4.0",
    "openai>=2.13.0",
    "pandas>=2.3.3",
    "polars[pyarrow]>=1.36.1",
    "python-lsp-ruff>=2.3.0",
    "python-lsp-server>=1.14.0",
    "sqlglot>=28.4.1",
    "websockets>=15.0.1",
]
